"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 載入 .env（放在專案根目錄 BASE_DIR 下，例如 cms/.env）
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 建議改用環境變數設定，未設定時使用開發用預設值
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-csk2@m1zj_vog&4ry8b(8%70gk=763e3frdgsjnba%1mp%r1ui')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',  # 圖片縮圖功能
    'filer',  # 檔案管理系統
    'mptt',  # 樹狀結構支援 (django-filer 依賴)
    'nested_admin',  # 巢狀內聯管理
    'ckeditor',  # 富文本編輯器
    'ckeditor_uploader',  # 富文本編輯器上傳功能
    'storages',  # S3 儲存支援 (django-storages)
    'main',  # 潛水套票應用程式
    'homepage',  # 首頁應用程式
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# 靜態檔案設定
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 媒體檔案設定（預設本機，若啟用 S3，會在下方覆蓋 MEDIA_URL）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 語言設定
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor 設定
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_THUMBNAIL_SIZE = (300, 300)
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_BROWSE_SHOW_DIRS = True

# CKEditor 工具列配置
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'toolbar_Custom': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms', 'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField']},
            '/',
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
        ],
    },
    'basic': {
        'toolbar': 'Basic',
        'height': 200,
        'width': '100%',
    },
    'table': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Table', 'Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'height': 250,
        'width': '100%',
    }
}

# Django-Filer 設定
FILER_ENABLE_LOGGING = True
FILER_DEBUG = DEBUG

# 讓 Filer 的 public / private / 縮圖都使用 S3，與舊專案一致但移除不存在的 sns.utils 依賴
FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'location': 'filer_public',
                'file_overwrite': True,
            },
            # 'UPLOAD_TO': 'sns.utils.folder_based_upload_to',  # 舊專案專用，這裡不再使用以避免依賴不存在的模組
        },
        'thumbnails': {
            'ENGINE': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'location': 'filer_public_thumbnails',
                'file_overwrite': True,
            },
        },
    },
    'private': {
        'main': {
            'ENGINE': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'location': 'filer_private',
                'file_overwrite': False,
                'default_acl': 'private',
            },
            # 'UPLOAD_TO': 'sns.utils.folder_based_upload_to',  # 同上，暫不啟用
        },
        'thumbnails': {
            'ENGINE': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'location': 'filer_private_thumbnails',
                'file_overwrite': True,
                'default_acl': 'private',
            },
        },
    },
}

# 縮圖設定（以 S3 為儲存，並沿用舊專案較完整的配置，但不啟用 image_cropping 相關處理器）
THUMBNAIL_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
THUMBNAIL_BASEDIR = 'thumbnails'
THUMBNAIL_QUALITY = 85
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
THUMBNAIL_PRESERVE_EXTENSIONS = True
THUMBNAIL_CACHE_DIMENSIONS = True

# =========================
# Amazon S3 / django-storages 設定
# =========================
# 建議實務上改用環境變數讀取，避免將金鑰硬寫在程式碼中
# 例如：
# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
# 這裡先依照你提供的設定示範寫法

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'maldives-sns')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-southeast-1')
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', 'sunnseaholidaysmed.com')

AWS_S3_WEBSITE_ENDPOINT = f'{AWS_STORAGE_BUCKET_NAME}.s3-website-{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = 'public-read'
AWS_LOCATION = 'media'
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False

# 讓所有上傳的檔案（包含 django-filer）都存到 S3
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# 使用自訂網域作為媒體網址（可依需求改成 AWS_S3_WEBSITE_ENDPOINT）
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
