# Generated by Django 4.2 on 2025-10-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名稱')),
                ('description', models.TextField(blank=True, verbose_name='城市描述')),
                ('image', models.ImageField(blank=True, upload_to='cities/', verbose_name='城市圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='國家名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名稱')),
                ('description', models.TextField(blank=True, verbose_name='國家描述')),
                ('image', models.ImageField(blank=True, upload_to='countries/', verbose_name='國家圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '國家',
                'verbose_name_plural': '國家',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='標籤名稱')),
                ('color', models.CharField(default='#007bff', help_text='使用十六進位顏色代碼', max_length=7, verbose_name='標籤顏色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '套票特色標籤',
                'verbose_name_plural': '套票特色標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套票種類名稱')),
                ('description', models.TextField(blank=True, verbose_name='套票種類描述')),
                ('icon', models.CharField(blank=True, help_text='使用 Font Awesome 圖示類別', max_length=50, verbose_name='圖示')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='所屬城市')),
            ],
            options={
                'verbose_name': '套票種類',
                'verbose_name_plural': '套票種類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套票名稱')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副標題')),
                ('description', models.TextField(verbose_name='套票描述')),
                ('main_image', models.ImageField(upload_to='packages/', verbose_name='主要圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精選')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.packagetype', verbose_name='套票種類')),
                ('tags', models.ManyToManyField(blank=True, to='main.packagetag', verbose_name='套票特色')),
            ],
            options={
                'verbose_name': '套票',
                'verbose_name_plural': '套票',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='所屬國家'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
