# Generated by Django 4.2 on 2025-10-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名稱')),
                ('website', models.URLField(blank=True, verbose_name='酒店網站')),
                ('image', models.ImageField(blank=True, upload_to='hotelinfo/', verbose_name='酒店圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('hotel_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_info', to='main.package', verbose_name='所屬酒店')),
            ],
        ),
    ]
