# Generated by Django 4.2.7 on 2025-10-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hotelinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='flight_info',
            field=models.TextField(blank=True, verbose_name='航班信息'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='hotel_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_type', to='main.hotelinfo', verbose_name='所屬酒店'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='price_exclude_item',
            field=models.TextField(blank=True, verbose_name='價格不包含項目'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='price_include_item',
            field=models.TextField(blank=True, verbose_name='價格包含項目'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='tips',
            field=models.TextField(blank=True, verbose_name='小貼士'),
        ),
    ]
