# Generated by Django 4.2 on 2025-10-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_packagetype_flight_info_packagetype_hotel_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelinfo',
            options={'ordering': ['name'], 'verbose_name': '酒店信息', 'verbose_name_plural': '酒店信息'},
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='hotel_info',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建時間'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='hotel_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_info', to='main.package', verbose_name='所屬套票'),
        ),
    ]
