# Generated by Django 4.2 on 2025-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_hotelinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='free_format_table',
            field=models.JSONField(blank=True, help_text='可以存儲任何結構的表格資料，例如價格表、房型資訊等', null=True, verbose_name='自由格式表格'),
        ),
    ]
