# Generated by Django 4.2 on 2025-10-15 09:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_package_free_format_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rich_text_table',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='使用富文本編輯器創建表格，支援圖片、連結等豐富內容', null=True, verbose_name='富文本表格'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='城市描述'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='國家描述'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='套票描述'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='套票種類描述'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='flight_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='航班信息'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='price_exclude_item',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='價格不包含項目'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='price_include_item',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='價格包含項目'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='tips',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='小貼士'),
        ),
    ]
