# Generated by Django 4.2 on 2025-10-15 09:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_package_rich_text_table_alter_city_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='city',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='flight_info',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='price_exclude_item',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='price_include_item',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='tips',
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='所屬城市'),
        ),
        migrations.AddField(
            model_name='package',
            name='flight_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='航班信息'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_exclude_item',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='價格不包含項目'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_include_item',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='價格包含項目'),
        ),
        migrations.AddField(
            model_name='package',
            name='tips',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='小貼士'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='name',
            field=models.CharField(help_text='例如：潛水課程、船潛、岸潛等', max_length=100, verbose_name='套票種類名稱'),
        ),
    ]
