# Generated by Django 4.2 on 2025-10-16 03:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_packagetype_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='free_format_table',
            field=models.JSONField(blank=True, help_text='可以存儲任何結構的表格資料，例如價格表、房型資訊等', null=True, verbose_name='價格表'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rich_text_table',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='使用富文本編輯器創建表格，支援圖片、連結等豐富內容', null=True, verbose_name='價格表二'),
        ),
    ]
