# Generated by Django 4.2 on 2025-10-16 03:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_package_free_format_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='free_format_table',
        ),
        migrations.AddField(
            model_name='package',
            name='rich_text_table_one',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='使用富文本編輯器創建表格，支援圖片、連結等豐富內容', null=True, verbose_name='價格表一'),
        ),
    ]
