# Generated by Django 4.2 on 2025-10-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_package_rich_text_table_three'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, help_text='用於 URL 的英文代碼，例如：okinawa, tokyo', max_length=100, verbose_name='URL 代碼'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, help_text='用於 URL 的英文代碼，例如：japan, thailand', max_length=100, unique=True, verbose_name='URL 代碼'),
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, help_text='用於 URL 的英文代碼，例如：beginner-diving-course', max_length=200, verbose_name='URL 代碼'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name'), ('country', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('city', 'slug')},
        ),
    ]
