# Generated by Django 4.2 on 2025-10-16 07:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_city_unique_together_city_slug_country_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='大陸名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名稱')),
                ('slug', models.SlugField(blank=True, help_text='用於 URL 的英文代碼，例如：asia, europe', max_length=100, unique=True, verbose_name='URL 代碼')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='大陸描述')),
                ('image', models.ImageField(blank=True, upload_to='continents/', verbose_name='大陸圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '大陸',
                'verbose_name_plural': '大陸',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, help_text='用於 URL 的英文代碼，例如：japan, thailand', max_length=100, verbose_name='URL 代碼'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.continent', verbose_name='所屬大陸'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('continent', 'name'), ('continent', 'slug')},
        ),
    ]
