# Generated by Django 4.2 on 2025-10-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_continent_alter_country_slug_country_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_vaild_date',
            field=models.DateField(blank=True, null=True, verbose_name='價格有效日期'),
        ),
    ]
