# Generated by Django 4.2 on 2025-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_package_price_vaild_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='套票價格'),
        ),
    ]
