# Generated by Django 4.2 on 2025-10-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_text', models.CharField(help_text='例如：第1天、第2-3天等', max_length=200, verbose_name='期間文字')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='酒店名稱')),
                ('room_type', models.CharField(blank=True, help_text='例如：標準房、豪華房等', max_length=100, verbose_name='房型')),
                ('image', models.ImageField(blank=True, help_text='期間相關圖片', upload_to='periods/', verbose_name='期間圖片')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='此期間的價格', max_digits=10, null=True, verbose_name='價格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='main.package', verbose_name='所屬套票')),
            ],
            options={
                'verbose_name': '期間',
                'verbose_name_plural': '期間',
                'ordering': ['package', 'period_text'],
            },
        ),
        migrations.DeleteModel(
            name='hotelinfo',
        ),
    ]
