# Generated by Django 4.2 on 2025-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_period_hotel_name_remove_period_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='hotel_name',
            field=models.CharField(default='未指定酒店', max_length=200, verbose_name='酒店名稱'),
        ),
        migrations.AddField(
            model_name='period',
            name='image',
            field=models.ImageField(blank=True, help_text='期間相關圖片', upload_to='periods/', verbose_name='期間圖片'),
        ),
        migrations.AddField(
            model_name='period',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='此期間的價格', max_digits=10, null=True, verbose_name='價格'),
        ),
        migrations.AddField(
            model_name='period',
            name='room_type',
            field=models.CharField(blank=True, help_text='例如：標準房、豪華房等', max_length=100, verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_text',
            field=models.CharField(help_text='例如：第1天、第2-3天等', max_length=200, verbose_name='期間文字'),
        ),
        migrations.DeleteModel(
            name='PeriodHotelInfo',
        ),
    ]
