# Generated by Django 4.2 on 2025-10-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_periodhotelinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='price',
            field=models.CharField(blank=True, help_text='此期間的價格', max_length=100, null=True, verbose_name='價格'),
        ),
    ]
