# Generated by Django 4.2 on 2025-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_period_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='price',
            field=models.TextField(blank=True, help_text='此期間的價格', max_length=100, null=True, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='periodhotelinfo',
            name='price',
            field=models.TextField(blank=True, help_text='此期間的價格', max_length=100, null=True, verbose_name='價格'),
        ),
    ]
