# Generated by Django 4.2 on 2025-10-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_period_price_alter_periodhotelinfo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='酒店名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'ordering': ['period', 'hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='房間圖片')),
                ('image_description', models.CharField(blank=True, max_length=200, verbose_name='圖片說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '房間圖片',
                'verbose_name_plural': '房間圖片',
                'ordering': ['room_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='房間價格', max_length=100, verbose_name='價格')),
                ('price_description', models.CharField(blank=True, help_text='例如：旺季價格、淡季價格等', max_length=200, verbose_name='價格說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '房間價格',
                'verbose_name_plural': '房間價格',
                'ordering': ['room_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(help_text='例如：標準房、豪華房等', max_length=100, verbose_name='房型名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='main.hotel', verbose_name='所屬酒店')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
                'ordering': ['hotel', 'room_type_name'],
            },
        ),
        migrations.RemoveField(
            model_name='period',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='period',
            name='image',
        ),
        migrations.RemoveField(
            model_name='period',
            name='price',
        ),
        migrations.RemoveField(
            model_name='period',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='PeriodHotelInfo',
        ),
        migrations.AddField(
            model_name='roomprice',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.roomtype', verbose_name='所屬房型'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.roomtype', verbose_name='所屬房型'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='main.period', verbose_name='所屬期間'),
        ),
    ]
