# Generated by Django 4.2 on 2025-11-10 06:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('main', '0024_hotel_roomimage_roomprice_roomtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='例如：1、2、3 等', verbose_name='天數')),
                ('title', models.CharField(help_text='例如：抵達馬爾代夫、環島遊覽等', max_length=200, verbose_name='行程標題')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='詳細描述當天的活動安排', verbose_name='行程描述')),
                ('start_time', models.TimeField(blank=True, help_text='例如：09:00', null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, help_text='例如：17:00', null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, help_text='行程地點名稱', max_length=200, verbose_name='地點')),
                ('location_address', models.CharField(blank=True, max_length=300, verbose_name='地點地址')),
                ('meal_info', models.CharField(blank=True, help_text='例如：早餐、午餐、晚餐', max_length=200, verbose_name='餐食資訊')),
                ('accommodation', models.CharField(blank=True, help_text='當晚住宿地點', max_length=200, verbose_name='住宿資訊')),
                ('transportation', models.CharField(blank=True, help_text='例如：專車接送、渡輪等', max_length=200, verbose_name='交通方式')),
                ('notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='其他重要事項或提醒', verbose_name='備註說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越靠前', verbose_name='顯示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '每天行程',
                'verbose_name_plural': '每天行程',
                'ordering': ['package', 'day_number', 'display_order'],
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='rich_text_table_three',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='使用富文本編輯器創建表格，支援圖片、連結等豐富內容', null=True, verbose_name='備用表格'),
        ),
        migrations.CreateModel(
            name='ItineraryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='相片的簡短描述', max_length=200, verbose_name='相片說明')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越靠前', verbose_name='顯示順序')),
                ('is_featured', models.BooleanField(default=False, help_text='每個行程可以設定一張主要相片', verbose_name='是否為主要相片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image', filer.fields.image.FilerImageField(help_text='使用 Django-Filer 管理的相片', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_images', to=settings.FILER_IMAGE_MODEL, verbose_name='行程相片')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.dailyitinerary', verbose_name='所屬行程')),
            ],
            options={
                'verbose_name': '行程相片',
                'verbose_name_plural': '行程相片',
                'ordering': ['itinerary', 'display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyitinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_itineraries', to='main.package', verbose_name='所屬套票'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyitinerary',
            unique_together={('package', 'day_number')},
        ),
    ]
