# Generated by Django 4.2 on 2025-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_dailyitinerary_alter_package_rich_text_table_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitinerary',
            name='description',
            field=models.TextField(help_text='詳細描述當天的活動安排', verbose_name='行程描述'),
        ),
        migrations.AlterField(
            model_name='dailyitinerary',
            name='notes',
            field=models.TextField(blank=True, help_text='其他重要事項或提醒', verbose_name='備註說明'),
        ),
    ]
