# Generated by Django 4.2 on 2025-11-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_dailyitinerary_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyitinerary',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailyitinerary',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dailyitinerary',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='dailyitinerary',
            name='start_time',
        ),
    ]
