# Generated by Django 4.2.7 on 2025-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_dailyitinerary_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_secondary_featured',
            field=models.BooleanField(default=False, help_text='選擇後會在首頁的次要精選區塊顯示', verbose_name='是否為次要精選'),
        ),
    ]
