# Generated by Django 4.2 on 2025-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_package_is_secondary_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ai_prompt_description',
            field=models.TextField(blank=True, help_text='輸入提示詞讓 AI 自動生成套票描述', null=True, verbose_name='AI 提示詞（描述）'),
        ),
    ]
