# Generated by Django 4.2.7 on 2025-11-18 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='首頁設定', max_length=100, verbose_name='名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('hero_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Hero 圖片')),
            ],
            options={
                'verbose_name': '首頁設定',
                'verbose_name_plural': '首頁設定',
            },
        ),
    ]
