# Generated by Django 4.2.7 on 2025-11-18 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='（舊）單一 Hero 圖片'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='標題')),
                ('link_url', models.URLField(blank=True, verbose_name='連結網址')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='圖片')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='homepage.homepagesettings', verbose_name='首頁設定')),
            ],
            options={
                'verbose_name': 'Hero 圖片',
                'verbose_name_plural': 'Hero 圖片',
                'ordering': ['order', 'id'],
            },
        ),
    ]
